As a prerequisite to conducting analysis of the data, we must first assemble a clean dataset that is properly merged and contains relevant information.  As both the Baseball Savant and the Weather Underground data include a UTC time, we can merge data using this.  The Baseball Savant data gives an exact time (to the second) while the Weather Underground data gives a timestamp that indicates the data is valid from the previous reading up to and including the timestamp.  We must process the Weather Underground data ordered by station and time, and generate an explicit time range from the implied range that comes from the observation data and the ordering of the observation data.  We must also generate a cross referencing of home team to weather station.  In the 2018 baseball season, the Baseball Savant data set includes 721,190 records and 126,283 records in which the ball was put into play.  The _sv_id_ field was empty for 392,521 of the records and for 68,878 of the records in which the ball was put into play.  This field is necessary for merging with weather data so we must generate a value to use with the missing data.  Because the weather data has an implied granularity that ranges from a few minutes all the way up to nearly an hour, we only need to get each missing _sv_id_ value correct to within a few minutes to be considered clean for merging purposes.

In both the Baseball Savant data and the Weather Underground data, we must convert the UTC information and _sv_id_ information to a common format.  In the Baseball Savant data, the _sv_id_ (a text string) of `180410_182326` is converted to an integer value of `20180410182336`.  In the Weather Underground data, the _obsTimeLocal_ (a text string) of `2018-04-03 00:02:00` is converted to an integer value of `20180403000200`.  To join a specific Baseball Savant time to a Weather Underground time range, we join the two together such that the Baseball Savant time is _greater than_ the beginning of the Weather Underground time range and is also _less than or equal to_ the end of the Weather Underground time range.  We must also cross reference the home team in the Baseball Savant data to the weather station in the Weather Underground data.  This can only be done by generating our own cross reference data table:

```json
"home_team","weather_station","elevation_ft","true_pressure"
"ARI","KAZPHOEN469",1280,"N"
"ATL","KGAATLAN378",919,"Y"
"BAL","KMDBALTI156",32,"Y"
"BOS","KMABROOK5",39,"Y"
"CHC","KILCHICA60",610,"N"
"CWS","KILCHICA600",600,"N"
"CIN","KOHCINCI398",607,"N"
"CLE","KOHCLEVE180",730,"N"
"COL","KCODENVE78",5225,"N"
```

The formula for calculating air density is described in @bahill2019sb [pp180-182] and is an input to the ball trajectory code.  The three inputs to the calculation are the temperature, the humidity level, and the true station pressure.  The cross reference data table includes both the weather station elevation and our educated guess on whether or not the station is reporting the true station pressure.  If it not, we must convert the sea level corrected pressure to true station pressure, a formula for which is also described in @bahill2019sb [pp180-182].  We implemented the formulas in R code, as shown below.

```{r eval=FALSE}
svp <- function(temp_celcius) {
  numerator = (18.687 - (temp_celcius/234.5)) * temp_celcius
  denominator = 257.14 + temp_celcius
  4.5841 * (2.71828 ^ (numerator / denominator))
}

air_pressure <- function(temp_celcius,bp_mmHg_sea_level,altitude_ft) {
  numerator = (-9.80665*0.0289644*altitude_ft*0.3048)
  denominator = (8.31447*(temp_celcius+273.15))
  bp_mmHg_sea_level * (2.71828 ^ (numerator / denominator))
}

air_density <- function(temp_celcius,air_pressure_mmHg,svp_mmHg,humidity_percent) {
  part1 = 273/(temp_celcius+273)
  part2 = 0.379 * svp_mmHg * humidity_percent / 100
  part3 = (air_pressure_mmHg - part2) / 760
  1.2929 * part1 * part3
}
```
